### PR TITLE
Docker local registry

### PR DESCRIPTION
**Pull request by Jokeswar**
Issue #133

### CODE REVIEW

**Comment by mgax** [comment]
How are we going to solve the chicken-and-egg problem of bootstrapping the registry? It must be started with dockerd connected to the official docker hub, then dockerd needs to be configured to use the mirror instead. We need to document these steps, or automate them. And I suspect it's easier to automate them if we keep the registry outside of nomad.

**Comment by gabriel-v** [comment]
Yes, this PR doesn't contain instructions on jacking up the host `dockerd` to use `localhost:6665` as the first mirror and the official registry as the second mirror.
There's no "chicken and egg" problem: if the mirror is down, the daemon will use the next available mirror (the official one). When it eventually does become available, the daemon will use it instead.

**Comment by Jokeswar** [comment]
I added a README section that explains how to enable the local registry. It might just be fine if we leave Nomad do the start-up phase for the local mirror. I include a script `templates/registry-setup.sh` that gives dockerd the necessary config file and restarts the daemon so it can use the registry. The only way the script runs is if the user executes it. Is there any way to automate that?

**Comment by gabriel-v** [comment]
You could use a [raw exec](https://www.nomadproject.io/docs/drivers/raw_exec.html) batch job to run a `if ! diff daemon.json /etc/docker/deamon.json; then cp daemon.json /etc/docker && systemctl restart docker; fi`, but you'd risk the Nomad agent bugging out and dying afterwards. If we want to integrate this nicely and manage it ourselves, I'd do this in `liquidinvestigations/cluster`, since we seem to push host-level configuration over there.

**Comment by Jokeswar** [comment]
I am thinking of a work around. It might be overkill. What if we keep `raw_exec` and make it run a python script. Something like `python3 setup.py`:

```python3
pid = os.fork()
if pid == 0:
    sleep(1)
    os.system('bash registry-setup.sh')
    # we could skip the lines above and do it 
    # all with python alone. aka `json` and `os`
```
I am not sure if Nomad will just follow the parent and not care about the child. If that's true my thought is that the parent will finish it's thing and get cleaned by Nomad and the child will do the config and restart part. This should prevent Nomad from bugging out. What do you think @mgax @gabriel-v ?

**Comment by gabriel-v** [comment]
This is great work! We decided to leave this configurration in liquidinvestigations/cluster

**Pull request closed without merging**
